project_id = "ieqmsrrasdimpkdnvkfg"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
site_url = "http://localhost:8080"
additional_redirect_urls = [
  "http://localhost:8080",
  "http://localhost:8080/",
  "http://localhost:8080/dashboard",
  "http://localhost:8080/login",
  "https://ieqmsrrasdimpkdnvkfg.supabase.co/auth/v1/callback"
]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10
enable_signup = true

[auth.external.google]
enabled = true
client_id = "env(GOOGLE_OAUTH_CLIENT_ID)"
secret = "env(GOOGLE_OAUTH_SECRET)"
redirect_uri = "https://ieqmsrrasdimpkdnvkfg.supabase.co/auth/v1/callback"

[db]
port = 54322
major_version = 17

[studio]
enabled = true
port = 54323